enum PaymentMethodTypes {
  CREDIT_CARD = "CREDIT_CARD",
  PIX = "PIX",
  BANK_SLIP = "BANK_SLIP",
  TRANSFER = "TRANSFER"
}

enum ChargeStatusTypes {
  PAY = "PAY",
  PENDING = "PENDING",
  SCHEDULE = "SCHEDULE",
  ACCREDIT = "ACCREDIT",
  REFUND = "REFUND",
  MANUAL_DISCHARGE = "MANUAL_DISCHARGE",
  CHARGEBACK = "CHARGEBACK",
  COUNTERCHARGE = "COUNTERCHARGE",
  IN_PROGRESS = "IN_PROGRESS",
  AUTHORIZED = "AUTHORIZED",
  FAIL = "FAIL",
  CANCELED = "CANCELED"
}


enum RefundReasonTypes {
  DUPLICATE_CHARGE = "DUPLICATE_CHARGE",
  IMPROPER_CHARGE = "IMPROPER_CHARGE",
  COSTUMER_WITHDRAWAL = "COSTUMER_WITHDRAWAL",
  OTHERS = "OTHERS"

}

enum TransactionStatusTypes {
  IN_PROGRESS = "IN_PROGRESS",
  APPROVED = "APPROVED",
  REFUND = "REFUND",
  AUTHORIZED = "AUTHORIZED",
  MANUAL_DISCHARGE = "MANUAL_DISCHARGE",
  MANUAL_REFUND = "MANUAL_REFUND",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  NOT_APPROVED = "NOT_APPROVED",
  CHARGEBACK = "CHARGEBACK",
  COUNTERCHARGE = "COUNTERCHARGE",
  CANCELED = "CANCELED",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  UNDER_PAYMENT = "UNDER_PAYMENT",
  OVER_PAYMENT = "OVER_PAYMENT",
  FAIL = "FAIL",
  INVALID = "INVALID"
}

enum Environments {
  PRODUCTION = "PRODUCTION",
  SANDBOX = "SANDBOX",
  DEVELOPMENT = "DEVELOPMENT"

}

enum TransactionRequestTypes {
  ACCESSION = "ACCESSION",
  RECURRENT = "RECURRENT",
  LOOSE = "LOOSE"
}

enum TransactionResponseTypes {
  ACCESSION = "ACCESSION",
  RECURRENT = "RECURRENT",
  LOOSE = "LOOSE",
  MANUAL_DISCHARGE = "MANUAL_DISCHARGE",
  REFUND = "REFUND",
  CHARGEBACK = "CHARGEBACK",
  COUNTERCHARGE = "COUNTERCHARGE"
}

enum CardBrandTypes {
  VISA = "VISA",
  MASTERCARD = "MASTERCARD",
  ELO = "ELO",
  AMEX = "AMEX",
  DINERS = "DINERS",
  AURA = "AURA",
  DISCOVER = "DISCOVER",
  JCB = "JCB",
  HIPERCARD = "HIPERCARD",
  SOROCRED = "SOROCRED",
  CABAL = "CABAL",
  CREDSYSTEM = "CREDSYSTEM",
  BANESCARD = "BANESCARD",
  CREDZ = "CREDZ",
  OTHER = "OTHER"

}

export {
  PaymentMethodTypes,
  ChargeStatusTypes,
  RefundReasonTypes,
  TransactionStatusTypes,
  Environments,
  TransactionRequestTypes,
  TransactionResponseTypes,
  CardBrandTypes
};

